package com.turkcell.playcell.gamingplatform.api.enumtypes;

public enum ResponseCodeStrings {
	TOKEN_SUCCESS,
	BASIC_AUTH_FAIL,
	AUTH_FAIL_PERM_TOKEN,
	AUTH_FAIL_TEMP_TOKEN,
	AUTH_TOKEN_NOT_FOUND,
	AUTH_FAIL_MOBCON_TOKEN,
	PROCESS_ERROR,
	MSISDN_FORMAT_ERROR,
	PACKAGE_QUERY_ERROR,
	PACKAGE_QUERY_SUCCESS,
	GAME_URL_NULL,
	GAME_LIST_SUCCESS,
	EXCEPTION_ERROR
}
