package com.turkcell.playcell.gamingplatform.api.enumtypes;

public enum ResponseCodeStrings {
	BASIC_AUTH_FAIL,
	AUTH_FAIL_PERM_TOKEN,
	AUTH_FAIL_TEMP_TOKEN,
	AUTH_TOKEN_NOT_FOUND,
	AUTH_FAIL_MOBCON_TOKEN,
	PROCESS_ERROR,
	MSISDN_FORMAT_ERROR,
	PACKAGE_QUERY_ERROR,
	GAME_URL_NULL,
	EXCEPTION_ERROR,
	SUCCESS;
}
