//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceOrderManagementRequestException_QNAME = new QName("http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", "ServiceOrderManagementRequestException");
    private final static QName _NoApprovalResultFoundException_QNAME = new QName("http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", "NoApprovalResultFoundException");
    private final static QName _NoPayerMsisdnInfoFoundException_QNAME = new QName("http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", "NoPayerMsisdnInfoFoundException");
    private final static QName _NoUserMsisdnInfoFoundException_QNAME = new QName("http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", "NoUserMsisdnInfoFoundException");
    private final static QName _NoSubactionIdFoundException_QNAME = new QName("http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", "NoSubactionIdFoundException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SmResourceAttribute }
     * 
     */
    public SmResourceAttribute createSmResourceAttribute() {
        return new SmResourceAttribute();
    }

    /**
     * Create an instance of {@link CreateOrderRequest }
     * 
     */
    public CreateOrderRequest createCreateOrderRequest() {
        return new CreateOrderRequest();
    }

    /**
     * Create an instance of {@link SmOrderHeader }
     * 
     */
    public SmOrderHeader createSmOrderHeader() {
        return new SmOrderHeader();
    }

    /**
     * Create an instance of {@link SmCustomer }
     * 
     */
    public SmCustomer createSmCustomer() {
        return new SmCustomer();
    }

    /**
     * Create an instance of {@link SmOrderLine }
     * 
     */
    public SmOrderLine createSmOrderLine() {
        return new SmOrderLine();
    }

    /**
     * Create an instance of {@link SubmitOrderRequest }
     * 
     */
    public SubmitOrderRequest createSubmitOrderRequest() {
        return new SubmitOrderRequest();
    }

    /**
     * Create an instance of {@link SmSubmitOrderHeader }
     * 
     */
    public SmSubmitOrderHeader createSmSubmitOrderHeader() {
        return new SmSubmitOrderHeader();
    }

    /**
     * Create an instance of {@link SmUser }
     * 
     */
    public SmUser createSmUser() {
        return new SmUser();
    }

    /**
     * Create an instance of {@link SmEntryChannelApplication }
     * 
     */
    public SmEntryChannelApplication createSmEntryChannelApplication() {
        return new SmEntryChannelApplication();
    }

    /**
     * Create an instance of {@link SmSubmitCustomer }
     * 
     */
    public SmSubmitCustomer createSmSubmitCustomer() {
        return new SmSubmitCustomer();
    }

    /**
     * Create an instance of {@link SmSubmitOrderLine }
     * 
     */
    public SmSubmitOrderLine createSmSubmitOrderLine() {
        return new SmSubmitOrderLine();
    }

    /**
     * Create an instance of {@link ValidateRequest }
     * 
     */
    public ValidateRequest createValidateRequest() {
        return new ValidateRequest();
    }

    /**
     * Create an instance of {@link SendApprovalResultRequest }
     * 
     */
    public SendApprovalResultRequest createSendApprovalResultRequest() {
        return new SendApprovalResultRequest();
    }

    /**
     * Create an instance of {@link SOCallBackForServiceOrderManagementRequest }
     * 
     */
    public SOCallBackForServiceOrderManagementRequest createSOCallBackForServiceOrderManagementRequest() {
        return new SOCallBackForServiceOrderManagementRequest();
    }

    /**
     * Create an instance of {@link LifeCycleUpdateRequest }
     * 
     */
    public LifeCycleUpdateRequest createLifeCycleUpdateRequest() {
        return new LifeCycleUpdateRequest();
    }

    /**
     * Create an instance of {@link SmLifeCycleOrderHeader }
     * 
     */
    public SmLifeCycleOrderHeader createSmLifeCycleOrderHeader() {
        return new SmLifeCycleOrderHeader();
    }

    /**
     * Create an instance of {@link SmLifeCycleOrderLine }
     * 
     */
    public SmLifeCycleOrderLine createSmLifeCycleOrderLine() {
        return new SmLifeCycleOrderLine();
    }

    /**
     * Create an instance of {@link AccountUpdateRequest }
     * 
     */
    public AccountUpdateRequest createAccountUpdateRequest() {
        return new AccountUpdateRequest();
    }

    /**
     * Create an instance of {@link SmAccountUpdateOrderHeader }
     * 
     */
    public SmAccountUpdateOrderHeader createSmAccountUpdateOrderHeader() {
        return new SmAccountUpdateOrderHeader();
    }

    /**
     * Create an instance of {@link SmAccountUpdateOrderLine }
     * 
     */
    public SmAccountUpdateOrderLine createSmAccountUpdateOrderLine() {
        return new SmAccountUpdateOrderLine();
    }

    /**
     * Create an instance of {@link SendApprovalResultWithPaymentDetailRequest }
     * 
     */
    public SendApprovalResultWithPaymentDetailRequest createSendApprovalResultWithPaymentDetailRequest() {
        return new SendApprovalResultWithPaymentDetailRequest();
    }

    /**
     * Create an instance of {@link SmApprovalOrderHeader }
     * 
     */
    public SmApprovalOrderHeader createSmApprovalOrderHeader() {
        return new SmApprovalOrderHeader();
    }

    /**
     * Create an instance of {@link SmAttribute }
     * 
     */
    public SmAttribute createSmAttribute() {
        return new SmAttribute();
    }

    /**
     * Create an instance of {@link SmRejectInfo }
     * 
     */
    public SmRejectInfo createSmRejectInfo() {
        return new SmRejectInfo();
    }

    /**
     * Create an instance of {@link ServiceOrderManagementResponse }
     * 
     */
    public ServiceOrderManagementResponse createServiceOrderManagementResponse() {
        return new ServiceOrderManagementResponse();
    }

    /**
     * Create an instance of {@link ServiceOrderManagementResponseLine }
     * 
     */
    public ServiceOrderManagementResponseLine createServiceOrderManagementResponseLine() {
        return new ServiceOrderManagementResponseLine();
    }

    /**
     * Create an instance of {@link SOCallBackForServiceOrderManagementResponse }
     * 
     */
    public SOCallBackForServiceOrderManagementResponse createSOCallBackForServiceOrderManagementResponse() {
        return new SOCallBackForServiceOrderManagementResponse();
    }

    /**
     * Create an instance of {@link ServiceOrderManagementResponseLineItem }
     * 
     */
    public ServiceOrderManagementResponseLineItem createServiceOrderManagementResponseLineItem() {
        return new ServiceOrderManagementResponseLineItem();
    }

    /**
     * Create an instance of {@link SmBusinessInteraction }
     * 
     */
    public SmBusinessInteraction createSmBusinessInteraction() {
        return new SmBusinessInteraction();
    }

    /**
     * Create an instance of {@link SmBusinessInteractionInfo }
     * 
     */
    public SmBusinessInteractionInfo createSmBusinessInteractionInfo() {
        return new SmBusinessInteractionInfo();
    }

    /**
     * Create an instance of {@link SmBusinessInteractionApproval }
     * 
     */
    public SmBusinessInteractionApproval createSmBusinessInteractionApproval() {
        return new SmBusinessInteractionApproval();
    }

    /**
     * Create an instance of {@link SmBusinessInteractionError }
     * 
     */
    public SmBusinessInteractionError createSmBusinessInteractionError() {
        return new SmBusinessInteractionError();
    }

    /**
     * Create an instance of {@link SmChannelApplication }
     * 
     */
    public SmChannelApplication createSmChannelApplication() {
        return new SmChannelApplication();
    }

    /**
     * Create an instance of {@link SmSubmitChannelApplication }
     * 
     */
    public SmSubmitChannelApplication createSmSubmitChannelApplication() {
        return new SmSubmitChannelApplication();
    }

    /**
     * Create an instance of {@link SmSalesAgent }
     * 
     */
    public SmSalesAgent createSmSalesAgent() {
        return new SmSalesAgent();
    }

    /**
     * Create an instance of {@link SmDealer }
     * 
     */
    public SmDealer createSmDealer() {
        return new SmDealer();
    }

    /**
     * Create an instance of {@link SmLineUserCustomer }
     * 
     */
    public SmLineUserCustomer createSmLineUserCustomer() {
        return new SmLineUserCustomer();
    }

    /**
     * Create an instance of {@link SmGiftCustomer }
     * 
     */
    public SmGiftCustomer createSmGiftCustomer() {
        return new SmGiftCustomer();
    }

    /**
     * Create an instance of {@link SmSubmitGiftCustomer }
     * 
     */
    public SmSubmitGiftCustomer createSmSubmitGiftCustomer() {
        return new SmSubmitGiftCustomer();
    }

    /**
     * Create an instance of {@link SmIndividualCustomer }
     * 
     */
    public SmIndividualCustomer createSmIndividualCustomer() {
        return new SmIndividualCustomer();
    }

    /**
     * Create an instance of {@link SmCorporateCustomer }
     * 
     */
    public SmCorporateCustomer createSmCorporateCustomer() {
        return new SmCorporateCustomer();
    }

    /**
     * Create an instance of {@link SmIndividualCorporateCustomer }
     * 
     */
    public SmIndividualCorporateCustomer createSmIndividualCorporateCustomer() {
        return new SmIndividualCorporateCustomer();
    }

    /**
     * Create an instance of {@link SmGiftIndividualCorporateCustomer }
     * 
     */
    public SmGiftIndividualCorporateCustomer createSmGiftIndividualCorporateCustomer() {
        return new SmGiftIndividualCorporateCustomer();
    }

    /**
     * Create an instance of {@link SmAuthorizedPerson }
     * 
     */
    public SmAuthorizedPerson createSmAuthorizedPerson() {
        return new SmAuthorizedPerson();
    }

    /**
     * Create an instance of {@link SmCustomerServiceIdentifier }
     * 
     */
    public SmCustomerServiceIdentifier createSmCustomerServiceIdentifier() {
        return new SmCustomerServiceIdentifier();
    }

    /**
     * Create an instance of {@link SmGiftCorporateCustomer }
     * 
     */
    public SmGiftCorporateCustomer createSmGiftCorporateCustomer() {
        return new SmGiftCorporateCustomer();
    }

    /**
     * Create an instance of {@link SmSubmitGiftIndividualCustomer }
     * 
     */
    public SmSubmitGiftIndividualCustomer createSmSubmitGiftIndividualCustomer() {
        return new SmSubmitGiftIndividualCustomer();
    }

    /**
     * Create an instance of {@link SmSubmitGiftCorporateCustomer }
     * 
     */
    public SmSubmitGiftCorporateCustomer createSmSubmitGiftCorporateCustomer() {
        return new SmSubmitGiftCorporateCustomer();
    }

    /**
     * Create an instance of {@link SmSubmitGiftIndividualCorporateCustomer }
     * 
     */
    public SmSubmitGiftIndividualCorporateCustomer createSmSubmitGiftIndividualCorporateCustomer() {
        return new SmSubmitGiftIndividualCorporateCustomer();
    }

    /**
     * Create an instance of {@link SmServiceIdentifier }
     * 
     */
    public SmServiceIdentifier createSmServiceIdentifier() {
        return new SmServiceIdentifier();
    }

    /**
     * Create an instance of {@link SmOrderLineItem }
     * 
     */
    public SmOrderLineItem createSmOrderLineItem() {
        return new SmOrderLineItem();
    }

    /**
     * Create an instance of {@link SmSubmitNotificationDetail }
     * 
     */
    public SmSubmitNotificationDetail createSmSubmitNotificationDetail() {
        return new SmSubmitNotificationDetail();
    }

    /**
     * Create an instance of {@link SmSubmitOrderLineDistinctConfirmationType }
     * 
     */
    public SmSubmitOrderLineDistinctConfirmationType createSmSubmitOrderLineDistinctConfirmationType() {
        return new SmSubmitOrderLineDistinctConfirmationType();
    }

    /**
     * Create an instance of {@link SmSubmitOrderLineItem }
     * 
     */
    public SmSubmitOrderLineItem createSmSubmitOrderLineItem() {
        return new SmSubmitOrderLineItem();
    }

    /**
     * Create an instance of {@link SmSubmitMplusSubscription }
     * 
     */
    public SmSubmitMplusSubscription createSmSubmitMplusSubscription() {
        return new SmSubmitMplusSubscription();
    }

    /**
     * Create an instance of {@link SmSubmitMplusSubscriptionInfo }
     * 
     */
    public SmSubmitMplusSubscriptionInfo createSmSubmitMplusSubscriptionInfo() {
        return new SmSubmitMplusSubscriptionInfo();
    }

    /**
     * Create an instance of {@link SmSubmitCampaignProfileItem }
     * 
     */
    public SmSubmitCampaignProfileItem createSmSubmitCampaignProfileItem() {
        return new SmSubmitCampaignProfileItem();
    }

    /**
     * Create an instance of {@link SmSubmitReplenishmentProfile }
     * 
     */
    public SmSubmitReplenishmentProfile createSmSubmitReplenishmentProfile() {
        return new SmSubmitReplenishmentProfile();
    }

    /**
     * Create an instance of {@link SmSubmitSubscriberProvParameters }
     * 
     */
    public SmSubmitSubscriberProvParameters createSmSubmitSubscriberProvParameters() {
        return new SmSubmitSubscriberProvParameters();
    }

    /**
     * Create an instance of {@link SmProductExternalDetails }
     * 
     */
    public SmProductExternalDetails createSmProductExternalDetails() {
        return new SmProductExternalDetails();
    }

    /**
     * Create an instance of {@link SmPeriodind }
     * 
     */
    public SmPeriodind createSmPeriodind() {
        return new SmPeriodind();
    }

    /**
     * Create an instance of {@link SmTechnicalElement }
     * 
     */
    public SmTechnicalElement createSmTechnicalElement() {
        return new SmTechnicalElement();
    }

    /**
     * Create an instance of {@link SmSubmitTechnicalElement }
     * 
     */
    public SmSubmitTechnicalElement createSmSubmitTechnicalElement() {
        return new SmSubmitTechnicalElement();
    }

    /**
     * Create an instance of {@link SmResource }
     * 
     */
    public SmResource createSmResource() {
        return new SmResource();
    }

    /**
     * Create an instance of {@link SmOptionalService }
     * 
     */
    public SmOptionalService createSmOptionalService() {
        return new SmOptionalService();
    }

    /**
     * Create an instance of {@link SmEndDateShiftInd }
     * 
     */
    public SmEndDateShiftInd createSmEndDateShiftInd() {
        return new SmEndDateShiftInd();
    }

    /**
     * Create an instance of {@link SmLifeCycleOrderLineItem }
     * 
     */
    public SmLifeCycleOrderLineItem createSmLifeCycleOrderLineItem() {
        return new SmLifeCycleOrderLineItem();
    }

    /**
     * Create an instance of {@link SmLifeCycleCampaignProfileItem }
     * 
     */
    public SmLifeCycleCampaignProfileItem createSmLifeCycleCampaignProfileItem() {
        return new SmLifeCycleCampaignProfileItem();
    }

    /**
     * Create an instance of {@link SmLifeCycleReplenishmentProfile }
     * 
     */
    public SmLifeCycleReplenishmentProfile createSmLifeCycleReplenishmentProfile() {
        return new SmLifeCycleReplenishmentProfile();
    }

    /**
     * Create an instance of {@link SmAccountUpdateNumberChangeParameters }
     * 
     */
    public SmAccountUpdateNumberChangeParameters createSmAccountUpdateNumberChangeParameters() {
        return new SmAccountUpdateNumberChangeParameters();
    }

    /**
     * Create an instance of {@link SmAccountUpdateOrderLineItem }
     * 
     */
    public SmAccountUpdateOrderLineItem createSmAccountUpdateOrderLineItem() {
        return new SmAccountUpdateOrderLineItem();
    }

    /**
     * Create an instance of {@link SmApprovalChannelApplication }
     * 
     */
    public SmApprovalChannelApplication createSmApprovalChannelApplication() {
        return new SmApprovalChannelApplication();
    }

    /**
     * Create an instance of {@link SmApprovalUser }
     * 
     */
    public SmApprovalUser createSmApprovalUser() {
        return new SmApprovalUser();
    }

    /**
     * Create an instance of {@link SmCatalogEntityResourceAttributesForECS }
     * 
     */
    public SmCatalogEntityResourceAttributesForECS createSmCatalogEntityResourceAttributesForECS() {
        return new SmCatalogEntityResourceAttributesForECS();
    }

    /**
     * Create an instance of {@link SmLcOfferAttributeValue }
     * 
     */
    public SmLcOfferAttributeValue createSmLcOfferAttributeValue() {
        return new SmLcOfferAttributeValue();
    }

    /**
     * Create an instance of {@link SmPrOfferAttributeValue }
     * 
     */
    public SmPrOfferAttributeValue createSmPrOfferAttributeValue() {
        return new SmPrOfferAttributeValue();
    }

    /**
     * Create an instance of {@link SmResourceAttribute.ResourceValue }
     * 
     */
    public SmResourceAttribute.ResourceValue createSmResourceAttributeResourceValue() {
        return new SmResourceAttribute.ResourceValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", name = "ServiceOrderManagementRequestException")
    public JAXBElement<String> createServiceOrderManagementRequestException(String value) {
        return new JAXBElement<String>(_ServiceOrderManagementRequestException_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", name = "NoApprovalResultFoundException")
    public JAXBElement<String> createNoApprovalResultFoundException(String value) {
        return new JAXBElement<String>(_NoApprovalResultFoundException_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", name = "NoPayerMsisdnInfoFoundException")
    public JAXBElement<String> createNoPayerMsisdnInfoFoundException(String value) {
        return new JAXBElement<String>(_NoPayerMsisdnInfoFoundException_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", name = "NoUserMsisdnInfoFoundException")
    public JAXBElement<String> createNoUserMsisdnInfoFoundException(String value) {
        return new JAXBElement<String>(_NoUserMsisdnInfoFoundException_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagement_v1.0", name = "NoSubactionIdFoundException")
    public JAXBElement<String> createNoSubactionIdFoundException(String value) {
        return new JAXBElement<String>(_NoSubactionIdFoundException_QNAME, String.class, null, value);
    }

}
