//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for service-order-management-response-line-item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="service-order-management-response-line-item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="systemGenerated" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="businessInteraction" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-business-interaction"/&gt;
 *         &lt;element name="continue" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "service-order-management-response-line-item", propOrder = {
    "systemGenerated",
    "productId",
    "offerId",
    "action",
    "businessInteraction",
    "_continue"
})
public class ServiceOrderManagementResponseLineItem {

    protected boolean systemGenerated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger productId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger offerId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger action;
    @XmlElement(required = true)
    protected SmBusinessInteraction businessInteraction;
    @XmlElement(name = "continue")
    protected boolean _continue;

    /**
     * Gets the value of the systemGenerated property.
     * 
     */
    public boolean isSystemGenerated() {
        return systemGenerated;
    }

    /**
     * Sets the value of the systemGenerated property.
     * 
     */
    public void setSystemGenerated(boolean value) {
        this.systemGenerated = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductId(BigInteger value) {
        this.productId = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOfferId(BigInteger value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAction(BigInteger value) {
        this.action = value;
    }

    /**
     * Gets the value of the businessInteraction property.
     * 
     * @return
     *     possible object is
     *     {@link SmBusinessInteraction }
     *     
     */
    public SmBusinessInteraction getBusinessInteraction() {
        return businessInteraction;
    }

    /**
     * Sets the value of the businessInteraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmBusinessInteraction }
     *     
     */
    public void setBusinessInteraction(SmBusinessInteraction value) {
        this.businessInteraction = value;
    }

    /**
     * Gets the value of the continue property.
     * 
     */
    public boolean isContinue() {
        return _continue;
    }

    /**
     * Sets the value of the continue property.
     * 
     */
    public void setContinue(boolean value) {
        this._continue = value;
    }

}
