//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-account-update-number-change-parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-account-update-number-change-parameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="oldMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="simNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="oldSimNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-account-update-number-change-parameters", propOrder = {
    "oldMsisdn",
    "simNo",
    "oldSimNo"
})
public class SmAccountUpdateNumberChangeParameters {

    @XmlElement(required = true, nillable = true)
    protected String oldMsisdn;
    @XmlElement(required = true, nillable = true)
    protected String simNo;
    @XmlElement(required = true, nillable = true)
    protected String oldSimNo;

    /**
     * Gets the value of the oldMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldMsisdn() {
        return oldMsisdn;
    }

    /**
     * Sets the value of the oldMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldMsisdn(String value) {
        this.oldMsisdn = value;
    }

    /**
     * Gets the value of the simNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimNo() {
        return simNo;
    }

    /**
     * Sets the value of the simNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimNo(String value) {
        this.simNo = value;
    }

    /**
     * Gets the value of the oldSimNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldSimNo() {
        return oldSimNo;
    }

    /**
     * Sets the value of the oldSimNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldSimNo(String value) {
        this.oldSimNo = value;
    }

}
