//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-authorized-person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-authorized-person"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="authorizePersonType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="personalCustomer" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-individual-customer"/&gt;
 *         &lt;element name="gsmNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-authorized-person", propOrder = {
    "authorizePersonType",
    "personalCustomer",
    "gsmNo"
})
public class SmAuthorizedPerson {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger authorizePersonType;
    @XmlElement(required = true)
    protected SmIndividualCustomer personalCustomer;
    @XmlElement(required = true)
    protected String gsmNo;

    /**
     * Gets the value of the authorizePersonType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAuthorizePersonType() {
        return authorizePersonType;
    }

    /**
     * Sets the value of the authorizePersonType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAuthorizePersonType(BigInteger value) {
        this.authorizePersonType = value;
    }

    /**
     * Gets the value of the personalCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link SmIndividualCustomer }
     *     
     */
    public SmIndividualCustomer getPersonalCustomer() {
        return personalCustomer;
    }

    /**
     * Sets the value of the personalCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmIndividualCustomer }
     *     
     */
    public void setPersonalCustomer(SmIndividualCustomer value) {
        this.personalCustomer = value;
    }

    /**
     * Gets the value of the gsmNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGsmNo() {
        return gsmNo;
    }

    /**
     * Sets the value of the gsmNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGsmNo(String value) {
        this.gsmNo = value;
    }

}
