//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-business-interaction-approval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-business-interaction-approval"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="notificationId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="messageText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="approveLabel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rejectLabel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="criteriaId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-business-interaction-approval", propOrder = {
    "notificationId",
    "messageText",
    "approveLabel",
    "rejectLabel",
    "criteriaId"
})
public class SmBusinessInteractionApproval {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger notificationId;
    @XmlElement(required = true)
    protected String messageText;
    @XmlElement(required = true)
    protected String approveLabel;
    @XmlElement(required = true)
    protected String rejectLabel;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger criteriaId;

    /**
     * Gets the value of the notificationId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNotificationId() {
        return notificationId;
    }

    /**
     * Sets the value of the notificationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNotificationId(BigInteger value) {
        this.notificationId = value;
    }

    /**
     * Gets the value of the messageText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageText() {
        return messageText;
    }

    /**
     * Sets the value of the messageText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageText(String value) {
        this.messageText = value;
    }

    /**
     * Gets the value of the approveLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproveLabel() {
        return approveLabel;
    }

    /**
     * Sets the value of the approveLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproveLabel(String value) {
        this.approveLabel = value;
    }

    /**
     * Gets the value of the rejectLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectLabel() {
        return rejectLabel;
    }

    /**
     * Sets the value of the rejectLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectLabel(String value) {
        this.rejectLabel = value;
    }

    /**
     * Gets the value of the criteriaId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCriteriaId() {
        return criteriaId;
    }

    /**
     * Sets the value of the criteriaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCriteriaId(BigInteger value) {
        this.criteriaId = value;
    }

}
