//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-catalog-entity-resource-attributes-forECS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-catalog-entity-resource-attributes-forECS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="notSendPriorityOffer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lcOfferAttributeValueList" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-lc-offer-attribute-value" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="prOfferAttributeValueList" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-pr-offer-attribute-value" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-catalog-entity-resource-attributes-forECS", propOrder = {
    "notSendPriorityOffer",
    "lcOfferAttributeValueList",
    "prOfferAttributeValueList"
})
public class SmCatalogEntityResourceAttributesForECS {

    @XmlElement(required = true, nillable = true)
    protected String notSendPriorityOffer;
    protected List<SmLcOfferAttributeValue> lcOfferAttributeValueList;
    protected List<SmPrOfferAttributeValue> prOfferAttributeValueList;

    /**
     * Gets the value of the notSendPriorityOffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotSendPriorityOffer() {
        return notSendPriorityOffer;
    }

    /**
     * Sets the value of the notSendPriorityOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotSendPriorityOffer(String value) {
        this.notSendPriorityOffer = value;
    }

    /**
     * Gets the value of the lcOfferAttributeValueList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lcOfferAttributeValueList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLcOfferAttributeValueList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmLcOfferAttributeValue }
     * 
     * 
     */
    public List<SmLcOfferAttributeValue> getLcOfferAttributeValueList() {
        if (lcOfferAttributeValueList == null) {
            lcOfferAttributeValueList = new ArrayList<SmLcOfferAttributeValue>();
        }
        return this.lcOfferAttributeValueList;
    }

    /**
     * Gets the value of the prOfferAttributeValueList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prOfferAttributeValueList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrOfferAttributeValueList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmPrOfferAttributeValue }
     * 
     * 
     */
    public List<SmPrOfferAttributeValue> getPrOfferAttributeValueList() {
        if (prOfferAttributeValueList == null) {
            prOfferAttributeValueList = new ArrayList<SmPrOfferAttributeValue>();
        }
        return this.prOfferAttributeValueList;
    }

}
