//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-endDateShiftInd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-endDateShiftInd"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="endDateShiftType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endDateShiftValue" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-endDateShiftInd", propOrder = {
    "endDateShiftType",
    "endDateShiftValue"
})
public class SmEndDateShiftInd {

    @XmlElement(required = true)
    protected String endDateShiftType;
    @XmlElement(required = true)
    protected BigInteger endDateShiftValue;

    /**
     * Gets the value of the endDateShiftType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDateShiftType() {
        return endDateShiftType;
    }

    /**
     * Sets the value of the endDateShiftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDateShiftType(String value) {
        this.endDateShiftType = value;
    }

    /**
     * Gets the value of the endDateShiftValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndDateShiftValue() {
        return endDateShiftValue;
    }

    /**
     * Sets the value of the endDateShiftValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndDateShiftValue(BigInteger value) {
        this.endDateShiftValue = value;
    }

}
