//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-lc-offer-attribute-value complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-lc-offer-attribute-value"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lcOfferIdValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ECSOfferTypeValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PAMServiceTypeValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uaIdValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uaValValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="daIdValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="daValValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="daRelativeValValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="daUnitTypeValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="updateAction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fafListNameVal" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="technicalElementId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="resourceType" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="serviceVariantId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="addPercentageVolume" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="informNotificationEngineValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="appOfferId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-lc-offer-attribute-value", propOrder = {
    "lcOfferIdValue",
    "ecsOfferTypeValue",
    "pamServiceTypeValue",
    "uaIdValue",
    "uaValValue",
    "daIdValue",
    "daValValue",
    "daRelativeValValue",
    "daUnitTypeValue",
    "updateAction",
    "fafListNameVal",
    "technicalElementId",
    "resourceId",
    "resourceType",
    "serviceVariantId",
    "addPercentageVolume",
    "informNotificationEngineValue",
    "appOfferId"
})
public class SmLcOfferAttributeValue {

    @XmlElement(required = true, nillable = true)
    protected String lcOfferIdValue;
    @XmlElement(name = "ECSOfferTypeValue", required = true, nillable = true)
    protected String ecsOfferTypeValue;
    @XmlElement(name = "PAMServiceTypeValue", required = true, nillable = true)
    protected String pamServiceTypeValue;
    @XmlElement(required = true, nillable = true)
    protected String uaIdValue;
    @XmlElement(required = true, nillable = true)
    protected String uaValValue;
    @XmlElement(required = true, nillable = true)
    protected String daIdValue;
    @XmlElement(required = true, nillable = true)
    protected String daValValue;
    @XmlElement(required = true, nillable = true)
    protected String daRelativeValValue;
    @XmlElement(required = true, nillable = true)
    protected String daUnitTypeValue;
    @XmlElement(required = true, nillable = true)
    protected String updateAction;
    @XmlElement(required = true, nillable = true)
    protected String fafListNameVal;
    @XmlElement(required = true, nillable = true)
    protected BigInteger technicalElementId;
    @XmlElement(required = true, nillable = true)
    protected BigInteger resourceId;
    @XmlElement(required = true, nillable = true)
    protected BigInteger resourceType;
    @XmlElement(required = true, nillable = true)
    protected BigInteger serviceVariantId;
    @XmlElement(required = true, nillable = true)
    protected String addPercentageVolume;
    @XmlElement(required = true, nillable = true)
    protected String informNotificationEngineValue;
    @XmlElement(required = true, nillable = true)
    protected BigInteger appOfferId;

    /**
     * Gets the value of the lcOfferIdValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcOfferIdValue() {
        return lcOfferIdValue;
    }

    /**
     * Sets the value of the lcOfferIdValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcOfferIdValue(String value) {
        this.lcOfferIdValue = value;
    }

    /**
     * Gets the value of the ecsOfferTypeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECSOfferTypeValue() {
        return ecsOfferTypeValue;
    }

    /**
     * Sets the value of the ecsOfferTypeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECSOfferTypeValue(String value) {
        this.ecsOfferTypeValue = value;
    }

    /**
     * Gets the value of the pamServiceTypeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAMServiceTypeValue() {
        return pamServiceTypeValue;
    }

    /**
     * Sets the value of the pamServiceTypeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAMServiceTypeValue(String value) {
        this.pamServiceTypeValue = value;
    }

    /**
     * Gets the value of the uaIdValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUaIdValue() {
        return uaIdValue;
    }

    /**
     * Sets the value of the uaIdValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUaIdValue(String value) {
        this.uaIdValue = value;
    }

    /**
     * Gets the value of the uaValValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUaValValue() {
        return uaValValue;
    }

    /**
     * Sets the value of the uaValValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUaValValue(String value) {
        this.uaValValue = value;
    }

    /**
     * Gets the value of the daIdValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaIdValue() {
        return daIdValue;
    }

    /**
     * Sets the value of the daIdValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaIdValue(String value) {
        this.daIdValue = value;
    }

    /**
     * Gets the value of the daValValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaValValue() {
        return daValValue;
    }

    /**
     * Sets the value of the daValValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaValValue(String value) {
        this.daValValue = value;
    }

    /**
     * Gets the value of the daRelativeValValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaRelativeValValue() {
        return daRelativeValValue;
    }

    /**
     * Sets the value of the daRelativeValValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaRelativeValValue(String value) {
        this.daRelativeValValue = value;
    }

    /**
     * Gets the value of the daUnitTypeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaUnitTypeValue() {
        return daUnitTypeValue;
    }

    /**
     * Sets the value of the daUnitTypeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaUnitTypeValue(String value) {
        this.daUnitTypeValue = value;
    }

    /**
     * Gets the value of the updateAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateAction() {
        return updateAction;
    }

    /**
     * Sets the value of the updateAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateAction(String value) {
        this.updateAction = value;
    }

    /**
     * Gets the value of the fafListNameVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFafListNameVal() {
        return fafListNameVal;
    }

    /**
     * Sets the value of the fafListNameVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFafListNameVal(String value) {
        this.fafListNameVal = value;
    }

    /**
     * Gets the value of the technicalElementId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTechnicalElementId() {
        return technicalElementId;
    }

    /**
     * Sets the value of the technicalElementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTechnicalElementId(BigInteger value) {
        this.technicalElementId = value;
    }

    /**
     * Gets the value of the resourceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResourceId() {
        return resourceId;
    }

    /**
     * Sets the value of the resourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResourceId(BigInteger value) {
        this.resourceId = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResourceType(BigInteger value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the serviceVariantId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServiceVariantId() {
        return serviceVariantId;
    }

    /**
     * Sets the value of the serviceVariantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServiceVariantId(BigInteger value) {
        this.serviceVariantId = value;
    }

    /**
     * Gets the value of the addPercentageVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddPercentageVolume() {
        return addPercentageVolume;
    }

    /**
     * Sets the value of the addPercentageVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddPercentageVolume(String value) {
        this.addPercentageVolume = value;
    }

    /**
     * Gets the value of the informNotificationEngineValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformNotificationEngineValue() {
        return informNotificationEngineValue;
    }

    /**
     * Sets the value of the informNotificationEngineValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformNotificationEngineValue(String value) {
        this.informNotificationEngineValue = value;
    }

    /**
     * Gets the value of the appOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAppOfferId() {
        return appOfferId;
    }

    /**
     * Sets the value of the appOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAppOfferId(BigInteger value) {
        this.appOfferId = value;
    }

}
