//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sm-life-cycle-order-line-item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-life-cycle-order-line-item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="vasUniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="currentIntervalId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="pendingEventId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="finalPrice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="oldStatusId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="newStatusId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="prorateMigration" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="notificationReason" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="prevNextChargingDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="replenishmentProfile" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-life-cycle-replenishment-profile"/&gt;
 *         &lt;element name="campaignProfile" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-life-cycle-campaign-profile-item" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-life-cycle-order-line-item", propOrder = {
    "offerId",
    "vasUniqueId",
    "currentIntervalId",
    "pendingEventId",
    "finalPrice",
    "oldStatusId",
    "newStatusId",
    "prorateMigration",
    "endDate",
    "notificationReason",
    "prevNextChargingDate",
    "replenishmentProfile",
    "campaignProfile"
})
public class SmLifeCycleOrderLineItem {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger offerId;
    @XmlElement(required = true)
    protected String vasUniqueId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger currentIntervalId;
    @XmlElement(required = true)
    protected String pendingEventId;
    @XmlElement(required = true)
    protected String finalPrice;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger oldStatusId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger newStatusId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger prorateMigration;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger notificationReason;
    @XmlElement(required = true)
    protected String prevNextChargingDate;
    @XmlElement(required = true)
    protected SmLifeCycleReplenishmentProfile replenishmentProfile;
    @XmlElement(required = true)
    protected List<SmLifeCycleCampaignProfileItem> campaignProfile;

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOfferId(BigInteger value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the vasUniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVasUniqueId() {
        return vasUniqueId;
    }

    /**
     * Sets the value of the vasUniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVasUniqueId(String value) {
        this.vasUniqueId = value;
    }

    /**
     * Gets the value of the currentIntervalId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCurrentIntervalId() {
        return currentIntervalId;
    }

    /**
     * Sets the value of the currentIntervalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCurrentIntervalId(BigInteger value) {
        this.currentIntervalId = value;
    }

    /**
     * Gets the value of the pendingEventId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingEventId() {
        return pendingEventId;
    }

    /**
     * Sets the value of the pendingEventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingEventId(String value) {
        this.pendingEventId = value;
    }

    /**
     * Gets the value of the finalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalPrice() {
        return finalPrice;
    }

    /**
     * Sets the value of the finalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalPrice(String value) {
        this.finalPrice = value;
    }

    /**
     * Gets the value of the oldStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOldStatusId() {
        return oldStatusId;
    }

    /**
     * Sets the value of the oldStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOldStatusId(BigInteger value) {
        this.oldStatusId = value;
    }

    /**
     * Gets the value of the newStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNewStatusId() {
        return newStatusId;
    }

    /**
     * Sets the value of the newStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNewStatusId(BigInteger value) {
        this.newStatusId = value;
    }

    /**
     * Gets the value of the prorateMigration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProrateMigration() {
        return prorateMigration;
    }

    /**
     * Sets the value of the prorateMigration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProrateMigration(BigInteger value) {
        this.prorateMigration = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the notificationReason property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNotificationReason() {
        return notificationReason;
    }

    /**
     * Sets the value of the notificationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNotificationReason(BigInteger value) {
        this.notificationReason = value;
    }

    /**
     * Gets the value of the prevNextChargingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevNextChargingDate() {
        return prevNextChargingDate;
    }

    /**
     * Sets the value of the prevNextChargingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevNextChargingDate(String value) {
        this.prevNextChargingDate = value;
    }

    /**
     * Gets the value of the replenishmentProfile property.
     * 
     * @return
     *     possible object is
     *     {@link SmLifeCycleReplenishmentProfile }
     *     
     */
    public SmLifeCycleReplenishmentProfile getReplenishmentProfile() {
        return replenishmentProfile;
    }

    /**
     * Sets the value of the replenishmentProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmLifeCycleReplenishmentProfile }
     *     
     */
    public void setReplenishmentProfile(SmLifeCycleReplenishmentProfile value) {
        this.replenishmentProfile = value;
    }

    /**
     * Gets the value of the campaignProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the campaignProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCampaignProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmLifeCycleCampaignProfileItem }
     * 
     * 
     */
    public List<SmLifeCycleCampaignProfileItem> getCampaignProfile() {
        if (campaignProfile == null) {
            campaignProfile = new ArrayList<SmLifeCycleCampaignProfileItem>();
        }
        return this.campaignProfile;
    }

}
