//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-life-cycle-replenishment-profile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-life-cycle-replenishment-profile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="replenishmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="replenishmentStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="replenishmentEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subscriptionBcCount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chargingBcCount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="campaignId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-life-cycle-replenishment-profile", propOrder = {
    "replenishmentStatus",
    "replenishmentStartDate",
    "replenishmentEndDate",
    "subscriptionBcCount",
    "chargingBcCount",
    "offerId",
    "campaignId"
})
public class SmLifeCycleReplenishmentProfile {

    @XmlElement(required = true)
    protected String replenishmentStatus;
    @XmlElement(required = true)
    protected String replenishmentStartDate;
    @XmlElement(required = true)
    protected String replenishmentEndDate;
    @XmlElement(required = true)
    protected String subscriptionBcCount;
    @XmlElement(required = true)
    protected String chargingBcCount;
    @XmlElement(required = true)
    protected String offerId;
    @XmlElement(required = true)
    protected String campaignId;

    /**
     * Gets the value of the replenishmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplenishmentStatus() {
        return replenishmentStatus;
    }

    /**
     * Sets the value of the replenishmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplenishmentStatus(String value) {
        this.replenishmentStatus = value;
    }

    /**
     * Gets the value of the replenishmentStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplenishmentStartDate() {
        return replenishmentStartDate;
    }

    /**
     * Sets the value of the replenishmentStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplenishmentStartDate(String value) {
        this.replenishmentStartDate = value;
    }

    /**
     * Gets the value of the replenishmentEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplenishmentEndDate() {
        return replenishmentEndDate;
    }

    /**
     * Sets the value of the replenishmentEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplenishmentEndDate(String value) {
        this.replenishmentEndDate = value;
    }

    /**
     * Gets the value of the subscriptionBcCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionBcCount() {
        return subscriptionBcCount;
    }

    /**
     * Sets the value of the subscriptionBcCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionBcCount(String value) {
        this.subscriptionBcCount = value;
    }

    /**
     * Gets the value of the chargingBcCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargingBcCount() {
        return chargingBcCount;
    }

    /**
     * Sets the value of the chargingBcCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargingBcCount(String value) {
        this.chargingBcCount = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferId(String value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the campaignId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * Sets the value of the campaignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampaignId(String value) {
        this.campaignId = value;
    }

}
