//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sm-order-line-item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-order-line-item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subscriptionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="startPeriodInd" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-periodind"/&gt;
 *         &lt;element name="endPeriodInd" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-periodind"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="campaignId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="actionReason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="reasonId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="riosExternalId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mainMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="technicalElement" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-technical-element" maxOccurs="unbounded"/&gt;
 *         &lt;element name="attribute" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-attribute" maxOccurs="unbounded"/&gt;
 *         &lt;element name="optionalService" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-optionalService" maxOccurs="unbounded"/&gt;
 *         &lt;element name="endDateShiftInd" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-endDateShiftInd"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-order-line-item", propOrder = {
    "subscriptionId",
    "startPeriodInd",
    "endPeriodInd",
    "startDate",
    "endDate",
    "offerId",
    "campaignId",
    "action",
    "actionReason",
    "reasonId",
    "riosExternalId",
    "mainMsisdn",
    "technicalElement",
    "attribute",
    "optionalService",
    "endDateShiftInd"
})
public class SmOrderLineItem {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger subscriptionId;
    @XmlElement(required = true)
    protected SmPeriodind startPeriodInd;
    @XmlElement(required = true)
    protected SmPeriodind endPeriodInd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger offerId;
    @XmlElement(required = true)
    protected String campaignId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger action;
    @XmlElement(required = true)
    protected String actionReason;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger reasonId;
    @XmlElement(required = true)
    protected String riosExternalId;
    @XmlElement(required = true)
    protected String mainMsisdn;
    @XmlElement(required = true)
    protected List<SmTechnicalElement> technicalElement;
    @XmlElement(required = true)
    protected List<SmAttribute> attribute;
    @XmlElement(required = true)
    protected List<SmOptionalService> optionalService;
    @XmlElement(required = true)
    protected SmEndDateShiftInd endDateShiftInd;

    /**
     * Gets the value of the subscriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Sets the value of the subscriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubscriptionId(BigInteger value) {
        this.subscriptionId = value;
    }

    /**
     * Gets the value of the startPeriodInd property.
     * 
     * @return
     *     possible object is
     *     {@link SmPeriodind }
     *     
     */
    public SmPeriodind getStartPeriodInd() {
        return startPeriodInd;
    }

    /**
     * Sets the value of the startPeriodInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmPeriodind }
     *     
     */
    public void setStartPeriodInd(SmPeriodind value) {
        this.startPeriodInd = value;
    }

    /**
     * Gets the value of the endPeriodInd property.
     * 
     * @return
     *     possible object is
     *     {@link SmPeriodind }
     *     
     */
    public SmPeriodind getEndPeriodInd() {
        return endPeriodInd;
    }

    /**
     * Sets the value of the endPeriodInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmPeriodind }
     *     
     */
    public void setEndPeriodInd(SmPeriodind value) {
        this.endPeriodInd = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOfferId(BigInteger value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the campaignId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * Sets the value of the campaignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampaignId(String value) {
        this.campaignId = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAction(BigInteger value) {
        this.action = value;
    }

    /**
     * Gets the value of the actionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionReason() {
        return actionReason;
    }

    /**
     * Sets the value of the actionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionReason(String value) {
        this.actionReason = value;
    }

    /**
     * Gets the value of the reasonId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReasonId() {
        return reasonId;
    }

    /**
     * Sets the value of the reasonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReasonId(BigInteger value) {
        this.reasonId = value;
    }

    /**
     * Gets the value of the riosExternalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiosExternalId() {
        return riosExternalId;
    }

    /**
     * Sets the value of the riosExternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiosExternalId(String value) {
        this.riosExternalId = value;
    }

    /**
     * Gets the value of the mainMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainMsisdn() {
        return mainMsisdn;
    }

    /**
     * Sets the value of the mainMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainMsisdn(String value) {
        this.mainMsisdn = value;
    }

    /**
     * Gets the value of the technicalElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technicalElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnicalElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmTechnicalElement }
     * 
     * 
     */
    public List<SmTechnicalElement> getTechnicalElement() {
        if (technicalElement == null) {
            technicalElement = new ArrayList<SmTechnicalElement>();
        }
        return this.technicalElement;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmAttribute }
     * 
     * 
     */
    public List<SmAttribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<SmAttribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the optionalService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionalService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionalService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmOptionalService }
     * 
     * 
     */
    public List<SmOptionalService> getOptionalService() {
        if (optionalService == null) {
            optionalService = new ArrayList<SmOptionalService>();
        }
        return this.optionalService;
    }

    /**
     * Gets the value of the endDateShiftInd property.
     * 
     * @return
     *     possible object is
     *     {@link SmEndDateShiftInd }
     *     
     */
    public SmEndDateShiftInd getEndDateShiftInd() {
        return endDateShiftInd;
    }

    /**
     * Sets the value of the endDateShiftInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmEndDateShiftInd }
     *     
     */
    public void setEndDateShiftInd(SmEndDateShiftInd value) {
        this.endDateShiftInd = value;
    }

}
