//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-order-line complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-order-line"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="crmProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="lineOfferId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="crmProductType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="lineUserCustomer" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-line-user-customer"/&gt;
 *         &lt;element name="transfererMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="giftReceiverCustomer" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-gift-customer"/&gt;
 *         &lt;element name="triggeringProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="orderLineItem" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-order-line-item" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-order-line", propOrder = {
    "msisdn",
    "customerId",
    "contractId",
    "crmProductId",
    "lineOfferId",
    "crmProductType",
    "lineUserCustomer",
    "transfererMsisdn",
    "giftReceiverCustomer",
    "triggeringProductId",
    "orderLineItem"
})
public class SmOrderLine {

    @XmlElement(required = true)
    protected String msisdn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger customerId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger contractId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger crmProductId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lineOfferId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger crmProductType;
    @XmlElement(required = true)
    protected SmLineUserCustomer lineUserCustomer;
    @XmlElement(required = true)
    protected String transfererMsisdn;
    @XmlElement(required = true)
    protected SmGiftCustomer giftReceiverCustomer;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger triggeringProductId;
    @XmlElement(required = true)
    protected List<SmOrderLineItem> orderLineItem;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerId(BigInteger value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the contractId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContractId() {
        return contractId;
    }

    /**
     * Sets the value of the contractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContractId(BigInteger value) {
        this.contractId = value;
    }

    /**
     * Gets the value of the crmProductId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrmProductId() {
        return crmProductId;
    }

    /**
     * Sets the value of the crmProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrmProductId(BigInteger value) {
        this.crmProductId = value;
    }

    /**
     * Gets the value of the lineOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineOfferId() {
        return lineOfferId;
    }

    /**
     * Sets the value of the lineOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineOfferId(BigInteger value) {
        this.lineOfferId = value;
    }

    /**
     * Gets the value of the crmProductType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrmProductType() {
        return crmProductType;
    }

    /**
     * Sets the value of the crmProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrmProductType(BigInteger value) {
        this.crmProductType = value;
    }

    /**
     * Gets the value of the lineUserCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link SmLineUserCustomer }
     *     
     */
    public SmLineUserCustomer getLineUserCustomer() {
        return lineUserCustomer;
    }

    /**
     * Sets the value of the lineUserCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmLineUserCustomer }
     *     
     */
    public void setLineUserCustomer(SmLineUserCustomer value) {
        this.lineUserCustomer = value;
    }

    /**
     * Gets the value of the transfererMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransfererMsisdn() {
        return transfererMsisdn;
    }

    /**
     * Sets the value of the transfererMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransfererMsisdn(String value) {
        this.transfererMsisdn = value;
    }

    /**
     * Gets the value of the giftReceiverCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link SmGiftCustomer }
     *     
     */
    public SmGiftCustomer getGiftReceiverCustomer() {
        return giftReceiverCustomer;
    }

    /**
     * Sets the value of the giftReceiverCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmGiftCustomer }
     *     
     */
    public void setGiftReceiverCustomer(SmGiftCustomer value) {
        this.giftReceiverCustomer = value;
    }

    /**
     * Gets the value of the triggeringProductId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTriggeringProductId() {
        return triggeringProductId;
    }

    /**
     * Sets the value of the triggeringProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTriggeringProductId(BigInteger value) {
        this.triggeringProductId = value;
    }

    /**
     * Gets the value of the orderLineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmOrderLineItem }
     * 
     * 
     */
    public List<SmOrderLineItem> getOrderLineItem() {
        if (orderLineItem == null) {
            orderLineItem = new ArrayList<SmOrderLineItem>();
        }
        return this.orderLineItem;
    }

}
