//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-submit-campaign-profile-item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-submit-campaign-profile-item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="intervalId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="inactivationReason" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="commitmentDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nextChargingDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isDefaultCampaign" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="subscriptionBcCount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chargingBcCount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chargingIntervalStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subscriptionPaymentType" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-submit-campaign-profile-item", propOrder = {
    "id",
    "name",
    "startDate",
    "endDate",
    "status",
    "intervalId",
    "inactivationReason",
    "commitmentDate",
    "nextChargingDate",
    "isDefaultCampaign",
    "subscriptionBcCount",
    "chargingBcCount",
    "chargingIntervalStartDate",
    "subscriptionPaymentType"
})
public class SmSubmitCampaignProfileItem {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String startDate;
    @XmlElement(required = true)
    protected String endDate;
    protected int status;
    @XmlElement(required = true)
    protected String intervalId;
    protected int inactivationReason;
    @XmlElement(required = true)
    protected String commitmentDate;
    @XmlElement(required = true)
    protected String nextChargingDate;
    protected int isDefaultCampaign;
    @XmlElement(required = true)
    protected String subscriptionBcCount;
    @XmlElement(required = true)
    protected String chargingBcCount;
    @XmlElement(required = true)
    protected String chargingIntervalStartDate;
    @XmlElement(required = true)
    protected BigInteger subscriptionPaymentType;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    /**
     * Gets the value of the intervalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntervalId() {
        return intervalId;
    }

    /**
     * Sets the value of the intervalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntervalId(String value) {
        this.intervalId = value;
    }

    /**
     * Gets the value of the inactivationReason property.
     * 
     */
    public int getInactivationReason() {
        return inactivationReason;
    }

    /**
     * Sets the value of the inactivationReason property.
     * 
     */
    public void setInactivationReason(int value) {
        this.inactivationReason = value;
    }

    /**
     * Gets the value of the commitmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommitmentDate() {
        return commitmentDate;
    }

    /**
     * Sets the value of the commitmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitmentDate(String value) {
        this.commitmentDate = value;
    }

    /**
     * Gets the value of the nextChargingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextChargingDate() {
        return nextChargingDate;
    }

    /**
     * Sets the value of the nextChargingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextChargingDate(String value) {
        this.nextChargingDate = value;
    }

    /**
     * Gets the value of the isDefaultCampaign property.
     * 
     */
    public int getIsDefaultCampaign() {
        return isDefaultCampaign;
    }

    /**
     * Sets the value of the isDefaultCampaign property.
     * 
     */
    public void setIsDefaultCampaign(int value) {
        this.isDefaultCampaign = value;
    }

    /**
     * Gets the value of the subscriptionBcCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionBcCount() {
        return subscriptionBcCount;
    }

    /**
     * Sets the value of the subscriptionBcCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionBcCount(String value) {
        this.subscriptionBcCount = value;
    }

    /**
     * Gets the value of the chargingBcCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargingBcCount() {
        return chargingBcCount;
    }

    /**
     * Sets the value of the chargingBcCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargingBcCount(String value) {
        this.chargingBcCount = value;
    }

    /**
     * Gets the value of the chargingIntervalStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargingIntervalStartDate() {
        return chargingIntervalStartDate;
    }

    /**
     * Sets the value of the chargingIntervalStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargingIntervalStartDate(String value) {
        this.chargingIntervalStartDate = value;
    }

    /**
     * Gets the value of the subscriptionPaymentType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubscriptionPaymentType() {
        return subscriptionPaymentType;
    }

    /**
     * Sets the value of the subscriptionPaymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubscriptionPaymentType(BigInteger value) {
        this.subscriptionPaymentType = value;
    }

}
