//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sm-submit-order-line-item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-submit-order-line-item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="parentProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="subscriptionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="startPeriodInd" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-periodind"/&gt;
 *         &lt;element name="endPeriodInd" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-periodind"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="offerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="campaignId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="actionReason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="catalogProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="sdpaOfferId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="generationReason" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="lineItemNotification" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-notification-detail" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="flowStatus" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="flowCurrentProcess" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="codeId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="errorDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="technicalElement" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-technical-element" maxOccurs="unbounded"/&gt;
 *         &lt;element name="attribute" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-attribute" maxOccurs="unbounded"/&gt;
 *         &lt;element name="optionalService" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-optionalService" maxOccurs="unbounded"/&gt;
 *         &lt;element name="endDateShiftInd" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-endDateShiftInd"/&gt;
 *         &lt;element name="systemGenerated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="vasUniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creationCode" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="siblingOfferId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="currentIntervalId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="slcmStatus" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="slcmEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pendingSlcmEventId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="slcmOldStatus" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="subActionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="wfLabel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="wfCatalogLabel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="staticIp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="firstFlowInitializeDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="riosExternalId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mainMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="finalPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="provisioningCatalogTechnicalElementId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="optionNo" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="checkMgbApn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="customerTariffOfferId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gpProvEndPointID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hasActiveSubscription" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="serviceSubscriber" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="catalogSiblingOfferId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="provisioningRollback" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="catalogBasedProvisioning" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="provisioningSystem" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="catalogSiblingProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="prorateMigration" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="notificationReason" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="replenishmentProfile" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-replenishment-profile"/&gt;
 *         &lt;element name="campaignProfileItem" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-campaign-profile-item" maxOccurs="unbounded"/&gt;
 *         &lt;element name="rollBackCampaignProfileItem" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-campaign-profile-item" maxOccurs="unbounded"/&gt;
 *         &lt;element name="subscriberProvParameters" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-subscriberProv-parameters"/&gt;
 *         &lt;element name="mplusSubscription" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-mplus-subscription"/&gt;
 *         &lt;element name="currentCampaignProfileItem" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-campaign-profile-item"/&gt;
 *         &lt;element name="relatedCPCMProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" maxOccurs="unbounded"/&gt;
 *         &lt;element name="prevNextChargingDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-submit-order-line-item", propOrder = {
    "productId",
    "parentProductId",
    "subscriptionId",
    "startPeriodInd",
    "endPeriodInd",
    "startDate",
    "endDate",
    "offerId",
    "campaignId",
    "action",
    "actionReason",
    "catalogProductId",
    "sdpaOfferId",
    "generationReason",
    "lineItemNotification",
    "flowStatus",
    "flowCurrentProcess",
    "codeId",
    "errorCode",
    "errorDescription",
    "technicalElement",
    "attribute",
    "optionalService",
    "endDateShiftInd",
    "systemGenerated",
    "vasUniqueId",
    "creationCode",
    "siblingOfferId",
    "currentIntervalId",
    "slcmStatus",
    "slcmEndDate",
    "pendingSlcmEventId",
    "slcmOldStatus",
    "subActionId",
    "wfLabel",
    "wfCatalogLabel",
    "staticIp",
    "firstFlowInitializeDate",
    "riosExternalId",
    "mainMsisdn",
    "finalPrice",
    "provisioningCatalogTechnicalElementId",
    "optionNo",
    "checkMgbApn",
    "customerTariffOfferId",
    "gpProvEndPointID",
    "hasActiveSubscription",
    "serviceSubscriber",
    "catalogSiblingOfferId",
    "provisioningRollback",
    "catalogBasedProvisioning",
    "provisioningSystem",
    "catalogSiblingProductId",
    "prorateMigration",
    "notificationReason",
    "replenishmentProfile",
    "campaignProfileItem",
    "rollBackCampaignProfileItem",
    "subscriberProvParameters",
    "mplusSubscription",
    "currentCampaignProfileItem",
    "relatedCPCMProductId",
    "prevNextChargingDate"
})
public class SmSubmitOrderLineItem {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger productId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger parentProductId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger subscriptionId;
    @XmlElement(required = true)
    protected SmPeriodind startPeriodInd;
    @XmlElement(required = true)
    protected SmPeriodind endPeriodInd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger offerId;
    @XmlElement(required = true)
    protected String campaignId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger action;
    @XmlElement(required = true)
    protected String actionReason;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger catalogProductId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sdpaOfferId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger generationReason;
    protected List<SmSubmitNotificationDetail> lineItemNotification;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger flowStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger flowCurrentProcess;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger codeId;
    @XmlElement(required = true)
    protected String errorCode;
    @XmlElement(required = true)
    protected String errorDescription;
    @XmlElement(required = true)
    protected List<SmSubmitTechnicalElement> technicalElement;
    @XmlElement(required = true)
    protected List<SmAttribute> attribute;
    @XmlElement(required = true)
    protected List<SmOptionalService> optionalService;
    @XmlElement(required = true)
    protected SmEndDateShiftInd endDateShiftInd;
    protected Boolean systemGenerated;
    @XmlElement(required = true)
    protected String vasUniqueId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger creationCode;
    @XmlElement(required = true)
    protected String siblingOfferId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger currentIntervalId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger slcmStatus;
    @XmlElement(required = true)
    protected String slcmEndDate;
    @XmlElement(required = true)
    protected String pendingSlcmEventId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger slcmOldStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger subActionId;
    @XmlElement(required = true)
    protected String wfLabel;
    @XmlElement(required = true)
    protected String wfCatalogLabel;
    @XmlElement(required = true)
    protected String staticIp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar firstFlowInitializeDate;
    @XmlElement(required = true)
    protected String riosExternalId;
    @XmlElement(required = true)
    protected String mainMsisdn;
    @XmlElement(required = true)
    protected BigDecimal finalPrice;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger provisioningCatalogTechnicalElementId;
    @XmlElement(required = true)
    protected BigInteger optionNo;
    protected Boolean checkMgbApn;
    @XmlElement(required = true)
    protected String customerTariffOfferId;
    @XmlElement(required = true)
    protected String gpProvEndPointID;
    protected Boolean hasActiveSubscription;
    protected Boolean serviceSubscriber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger catalogSiblingOfferId;
    protected Boolean provisioningRollback;
    protected Boolean catalogBasedProvisioning;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger provisioningSystem;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger catalogSiblingProductId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger prorateMigration;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger notificationReason;
    @XmlElement(required = true)
    protected SmSubmitReplenishmentProfile replenishmentProfile;
    @XmlElement(required = true)
    protected List<SmSubmitCampaignProfileItem> campaignProfileItem;
    @XmlElement(required = true)
    protected List<SmSubmitCampaignProfileItem> rollBackCampaignProfileItem;
    @XmlElement(required = true)
    protected SmSubmitSubscriberProvParameters subscriberProvParameters;
    @XmlElement(required = true)
    protected SmSubmitMplusSubscription mplusSubscription;
    @XmlElement(required = true)
    protected SmSubmitCampaignProfileItem currentCampaignProfileItem;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected List<BigInteger> relatedCPCMProductId;
    @XmlElement(required = true)
    protected String prevNextChargingDate;

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductId(BigInteger value) {
        this.productId = value;
    }

    /**
     * Gets the value of the parentProductId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentProductId() {
        return parentProductId;
    }

    /**
     * Sets the value of the parentProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentProductId(BigInteger value) {
        this.parentProductId = value;
    }

    /**
     * Gets the value of the subscriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Sets the value of the subscriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubscriptionId(BigInteger value) {
        this.subscriptionId = value;
    }

    /**
     * Gets the value of the startPeriodInd property.
     * 
     * @return
     *     possible object is
     *     {@link SmPeriodind }
     *     
     */
    public SmPeriodind getStartPeriodInd() {
        return startPeriodInd;
    }

    /**
     * Sets the value of the startPeriodInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmPeriodind }
     *     
     */
    public void setStartPeriodInd(SmPeriodind value) {
        this.startPeriodInd = value;
    }

    /**
     * Gets the value of the endPeriodInd property.
     * 
     * @return
     *     possible object is
     *     {@link SmPeriodind }
     *     
     */
    public SmPeriodind getEndPeriodInd() {
        return endPeriodInd;
    }

    /**
     * Sets the value of the endPeriodInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmPeriodind }
     *     
     */
    public void setEndPeriodInd(SmPeriodind value) {
        this.endPeriodInd = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOfferId(BigInteger value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the campaignId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * Sets the value of the campaignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampaignId(String value) {
        this.campaignId = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAction(BigInteger value) {
        this.action = value;
    }

    /**
     * Gets the value of the actionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionReason() {
        return actionReason;
    }

    /**
     * Sets the value of the actionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionReason(String value) {
        this.actionReason = value;
    }

    /**
     * Gets the value of the catalogProductId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCatalogProductId() {
        return catalogProductId;
    }

    /**
     * Sets the value of the catalogProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCatalogProductId(BigInteger value) {
        this.catalogProductId = value;
    }

    /**
     * Gets the value of the sdpaOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSdpaOfferId() {
        return sdpaOfferId;
    }

    /**
     * Sets the value of the sdpaOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSdpaOfferId(BigInteger value) {
        this.sdpaOfferId = value;
    }

    /**
     * Gets the value of the generationReason property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGenerationReason() {
        return generationReason;
    }

    /**
     * Sets the value of the generationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGenerationReason(BigInteger value) {
        this.generationReason = value;
    }

    /**
     * Gets the value of the lineItemNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItemNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItemNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitNotificationDetail }
     * 
     * 
     */
    public List<SmSubmitNotificationDetail> getLineItemNotification() {
        if (lineItemNotification == null) {
            lineItemNotification = new ArrayList<SmSubmitNotificationDetail>();
        }
        return this.lineItemNotification;
    }

    /**
     * Gets the value of the flowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlowStatus() {
        return flowStatus;
    }

    /**
     * Sets the value of the flowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlowStatus(BigInteger value) {
        this.flowStatus = value;
    }

    /**
     * Gets the value of the flowCurrentProcess property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlowCurrentProcess() {
        return flowCurrentProcess;
    }

    /**
     * Sets the value of the flowCurrentProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlowCurrentProcess(BigInteger value) {
        this.flowCurrentProcess = value;
    }

    /**
     * Gets the value of the codeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodeId() {
        return codeId;
    }

    /**
     * Sets the value of the codeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodeId(BigInteger value) {
        this.codeId = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDescription() {
        return errorDescription;
    }

    /**
     * Sets the value of the errorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDescription(String value) {
        this.errorDescription = value;
    }

    /**
     * Gets the value of the technicalElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technicalElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnicalElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitTechnicalElement }
     * 
     * 
     */
    public List<SmSubmitTechnicalElement> getTechnicalElement() {
        if (technicalElement == null) {
            technicalElement = new ArrayList<SmSubmitTechnicalElement>();
        }
        return this.technicalElement;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmAttribute }
     * 
     * 
     */
    public List<SmAttribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<SmAttribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the optionalService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionalService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionalService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmOptionalService }
     * 
     * 
     */
    public List<SmOptionalService> getOptionalService() {
        if (optionalService == null) {
            optionalService = new ArrayList<SmOptionalService>();
        }
        return this.optionalService;
    }

    /**
     * Gets the value of the endDateShiftInd property.
     * 
     * @return
     *     possible object is
     *     {@link SmEndDateShiftInd }
     *     
     */
    public SmEndDateShiftInd getEndDateShiftInd() {
        return endDateShiftInd;
    }

    /**
     * Sets the value of the endDateShiftInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmEndDateShiftInd }
     *     
     */
    public void setEndDateShiftInd(SmEndDateShiftInd value) {
        this.endDateShiftInd = value;
    }

    /**
     * Gets the value of the systemGenerated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSystemGenerated() {
        return systemGenerated;
    }

    /**
     * Sets the value of the systemGenerated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSystemGenerated(Boolean value) {
        this.systemGenerated = value;
    }

    /**
     * Gets the value of the vasUniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVasUniqueId() {
        return vasUniqueId;
    }

    /**
     * Sets the value of the vasUniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVasUniqueId(String value) {
        this.vasUniqueId = value;
    }

    /**
     * Gets the value of the creationCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreationCode() {
        return creationCode;
    }

    /**
     * Sets the value of the creationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreationCode(BigInteger value) {
        this.creationCode = value;
    }

    /**
     * Gets the value of the siblingOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiblingOfferId() {
        return siblingOfferId;
    }

    /**
     * Sets the value of the siblingOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiblingOfferId(String value) {
        this.siblingOfferId = value;
    }

    /**
     * Gets the value of the currentIntervalId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCurrentIntervalId() {
        return currentIntervalId;
    }

    /**
     * Sets the value of the currentIntervalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCurrentIntervalId(BigInteger value) {
        this.currentIntervalId = value;
    }

    /**
     * Gets the value of the slcmStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSlcmStatus() {
        return slcmStatus;
    }

    /**
     * Sets the value of the slcmStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSlcmStatus(BigInteger value) {
        this.slcmStatus = value;
    }

    /**
     * Gets the value of the slcmEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlcmEndDate() {
        return slcmEndDate;
    }

    /**
     * Sets the value of the slcmEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlcmEndDate(String value) {
        this.slcmEndDate = value;
    }

    /**
     * Gets the value of the pendingSlcmEventId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingSlcmEventId() {
        return pendingSlcmEventId;
    }

    /**
     * Sets the value of the pendingSlcmEventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingSlcmEventId(String value) {
        this.pendingSlcmEventId = value;
    }

    /**
     * Gets the value of the slcmOldStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSlcmOldStatus() {
        return slcmOldStatus;
    }

    /**
     * Sets the value of the slcmOldStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSlcmOldStatus(BigInteger value) {
        this.slcmOldStatus = value;
    }

    /**
     * Gets the value of the subActionId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubActionId() {
        return subActionId;
    }

    /**
     * Sets the value of the subActionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubActionId(BigInteger value) {
        this.subActionId = value;
    }

    /**
     * Gets the value of the wfLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfLabel() {
        return wfLabel;
    }

    /**
     * Sets the value of the wfLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfLabel(String value) {
        this.wfLabel = value;
    }

    /**
     * Gets the value of the wfCatalogLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWfCatalogLabel() {
        return wfCatalogLabel;
    }

    /**
     * Sets the value of the wfCatalogLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWfCatalogLabel(String value) {
        this.wfCatalogLabel = value;
    }

    /**
     * Gets the value of the staticIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaticIp() {
        return staticIp;
    }

    /**
     * Sets the value of the staticIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaticIp(String value) {
        this.staticIp = value;
    }

    /**
     * Gets the value of the firstFlowInitializeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstFlowInitializeDate() {
        return firstFlowInitializeDate;
    }

    /**
     * Sets the value of the firstFlowInitializeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstFlowInitializeDate(XMLGregorianCalendar value) {
        this.firstFlowInitializeDate = value;
    }

    /**
     * Gets the value of the riosExternalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiosExternalId() {
        return riosExternalId;
    }

    /**
     * Sets the value of the riosExternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiosExternalId(String value) {
        this.riosExternalId = value;
    }

    /**
     * Gets the value of the mainMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainMsisdn() {
        return mainMsisdn;
    }

    /**
     * Sets the value of the mainMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainMsisdn(String value) {
        this.mainMsisdn = value;
    }

    /**
     * Gets the value of the finalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinalPrice() {
        return finalPrice;
    }

    /**
     * Sets the value of the finalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinalPrice(BigDecimal value) {
        this.finalPrice = value;
    }

    /**
     * Gets the value of the provisioningCatalogTechnicalElementId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProvisioningCatalogTechnicalElementId() {
        return provisioningCatalogTechnicalElementId;
    }

    /**
     * Sets the value of the provisioningCatalogTechnicalElementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProvisioningCatalogTechnicalElementId(BigInteger value) {
        this.provisioningCatalogTechnicalElementId = value;
    }

    /**
     * Gets the value of the optionNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOptionNo() {
        return optionNo;
    }

    /**
     * Sets the value of the optionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOptionNo(BigInteger value) {
        this.optionNo = value;
    }

    /**
     * Gets the value of the checkMgbApn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckMgbApn() {
        return checkMgbApn;
    }

    /**
     * Sets the value of the checkMgbApn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckMgbApn(Boolean value) {
        this.checkMgbApn = value;
    }

    /**
     * Gets the value of the customerTariffOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerTariffOfferId() {
        return customerTariffOfferId;
    }

    /**
     * Sets the value of the customerTariffOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerTariffOfferId(String value) {
        this.customerTariffOfferId = value;
    }

    /**
     * Gets the value of the gpProvEndPointID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpProvEndPointID() {
        return gpProvEndPointID;
    }

    /**
     * Sets the value of the gpProvEndPointID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpProvEndPointID(String value) {
        this.gpProvEndPointID = value;
    }

    /**
     * Gets the value of the hasActiveSubscription property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasActiveSubscription() {
        return hasActiveSubscription;
    }

    /**
     * Sets the value of the hasActiveSubscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasActiveSubscription(Boolean value) {
        this.hasActiveSubscription = value;
    }

    /**
     * Gets the value of the serviceSubscriber property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServiceSubscriber() {
        return serviceSubscriber;
    }

    /**
     * Sets the value of the serviceSubscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServiceSubscriber(Boolean value) {
        this.serviceSubscriber = value;
    }

    /**
     * Gets the value of the catalogSiblingOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCatalogSiblingOfferId() {
        return catalogSiblingOfferId;
    }

    /**
     * Sets the value of the catalogSiblingOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCatalogSiblingOfferId(BigInteger value) {
        this.catalogSiblingOfferId = value;
    }

    /**
     * Gets the value of the provisioningRollback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProvisioningRollback() {
        return provisioningRollback;
    }

    /**
     * Sets the value of the provisioningRollback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProvisioningRollback(Boolean value) {
        this.provisioningRollback = value;
    }

    /**
     * Gets the value of the catalogBasedProvisioning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCatalogBasedProvisioning() {
        return catalogBasedProvisioning;
    }

    /**
     * Sets the value of the catalogBasedProvisioning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCatalogBasedProvisioning(Boolean value) {
        this.catalogBasedProvisioning = value;
    }

    /**
     * Gets the value of the provisioningSystem property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProvisioningSystem() {
        return provisioningSystem;
    }

    /**
     * Sets the value of the provisioningSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProvisioningSystem(BigInteger value) {
        this.provisioningSystem = value;
    }

    /**
     * Gets the value of the catalogSiblingProductId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCatalogSiblingProductId() {
        return catalogSiblingProductId;
    }

    /**
     * Sets the value of the catalogSiblingProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCatalogSiblingProductId(BigInteger value) {
        this.catalogSiblingProductId = value;
    }

    /**
     * Gets the value of the prorateMigration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProrateMigration() {
        return prorateMigration;
    }

    /**
     * Sets the value of the prorateMigration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProrateMigration(BigInteger value) {
        this.prorateMigration = value;
    }

    /**
     * Gets the value of the notificationReason property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNotificationReason() {
        return notificationReason;
    }

    /**
     * Sets the value of the notificationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNotificationReason(BigInteger value) {
        this.notificationReason = value;
    }

    /**
     * Gets the value of the replenishmentProfile property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitReplenishmentProfile }
     *     
     */
    public SmSubmitReplenishmentProfile getReplenishmentProfile() {
        return replenishmentProfile;
    }

    /**
     * Sets the value of the replenishmentProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitReplenishmentProfile }
     *     
     */
    public void setReplenishmentProfile(SmSubmitReplenishmentProfile value) {
        this.replenishmentProfile = value;
    }

    /**
     * Gets the value of the campaignProfileItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the campaignProfileItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCampaignProfileItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitCampaignProfileItem }
     * 
     * 
     */
    public List<SmSubmitCampaignProfileItem> getCampaignProfileItem() {
        if (campaignProfileItem == null) {
            campaignProfileItem = new ArrayList<SmSubmitCampaignProfileItem>();
        }
        return this.campaignProfileItem;
    }

    /**
     * Gets the value of the rollBackCampaignProfileItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rollBackCampaignProfileItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRollBackCampaignProfileItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitCampaignProfileItem }
     * 
     * 
     */
    public List<SmSubmitCampaignProfileItem> getRollBackCampaignProfileItem() {
        if (rollBackCampaignProfileItem == null) {
            rollBackCampaignProfileItem = new ArrayList<SmSubmitCampaignProfileItem>();
        }
        return this.rollBackCampaignProfileItem;
    }

    /**
     * Gets the value of the subscriberProvParameters property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitSubscriberProvParameters }
     *     
     */
    public SmSubmitSubscriberProvParameters getSubscriberProvParameters() {
        return subscriberProvParameters;
    }

    /**
     * Sets the value of the subscriberProvParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitSubscriberProvParameters }
     *     
     */
    public void setSubscriberProvParameters(SmSubmitSubscriberProvParameters value) {
        this.subscriberProvParameters = value;
    }

    /**
     * Gets the value of the mplusSubscription property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitMplusSubscription }
     *     
     */
    public SmSubmitMplusSubscription getMplusSubscription() {
        return mplusSubscription;
    }

    /**
     * Sets the value of the mplusSubscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitMplusSubscription }
     *     
     */
    public void setMplusSubscription(SmSubmitMplusSubscription value) {
        this.mplusSubscription = value;
    }

    /**
     * Gets the value of the currentCampaignProfileItem property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitCampaignProfileItem }
     *     
     */
    public SmSubmitCampaignProfileItem getCurrentCampaignProfileItem() {
        return currentCampaignProfileItem;
    }

    /**
     * Sets the value of the currentCampaignProfileItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitCampaignProfileItem }
     *     
     */
    public void setCurrentCampaignProfileItem(SmSubmitCampaignProfileItem value) {
        this.currentCampaignProfileItem = value;
    }

    /**
     * Gets the value of the relatedCPCMProductId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedCPCMProductId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedCPCMProductId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getRelatedCPCMProductId() {
        if (relatedCPCMProductId == null) {
            relatedCPCMProductId = new ArrayList<BigInteger>();
        }
        return this.relatedCPCMProductId;
    }

    /**
     * Gets the value of the prevNextChargingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevNextChargingDate() {
        return prevNextChargingDate;
    }

    /**
     * Sets the value of the prevNextChargingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevNextChargingDate(String value) {
        this.prevNextChargingDate = value;
    }

}
