//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sm-submit-order-line complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-submit-order-line"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="crmProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="lineOfferId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="crmProductType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="generationReason" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="lifecycleExtended" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="flowStatus" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="flowCurrentProcess" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="codeId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="confirmationType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="confirmationState" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="confirmationExpireDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="distinctConfirmationType" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-order-line-distinct-confirmation-type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="lineNotification" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-notification-detail" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="approveStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="productPaymentType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="oldMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="oldSimNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="newSimNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subActionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="lineUserCustomer" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-line-user-customer"/&gt;
 *         &lt;element name="transfererMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="giftReceiverCustomer" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-gift-customer"/&gt;
 *         &lt;element name="orderLineItem" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-order-line-item" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-submit-order-line", propOrder = {
    "productId",
    "msisdn",
    "customerId",
    "contractId",
    "crmProductId",
    "lineOfferId",
    "crmProductType",
    "productType",
    "generationReason",
    "lifecycleExtended",
    "flowStatus",
    "flowCurrentProcess",
    "codeId",
    "confirmationType",
    "confirmationState",
    "confirmationExpireDate",
    "distinctConfirmationType",
    "lineNotification",
    "approveStatus",
    "productPaymentType",
    "oldMsisdn",
    "oldSimNo",
    "newSimNo",
    "subActionId",
    "lineUserCustomer",
    "transfererMsisdn",
    "giftReceiverCustomer",
    "orderLineItem"
})
public class SmSubmitOrderLine {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger productId;
    @XmlElement(required = true)
    protected String msisdn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger customerId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger contractId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger crmProductId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lineOfferId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger crmProductType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger productType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger generationReason;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lifecycleExtended;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger flowStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger flowCurrentProcess;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger codeId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger confirmationType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger confirmationState;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar confirmationExpireDate;
    @XmlElement(required = true)
    protected List<SmSubmitOrderLineDistinctConfirmationType> distinctConfirmationType;
    protected List<SmSubmitNotificationDetail> lineNotification;
    protected Boolean approveStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger productPaymentType;
    @XmlElement(required = true)
    protected String oldMsisdn;
    @XmlElement(required = true)
    protected String oldSimNo;
    @XmlElement(required = true)
    protected String newSimNo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger subActionId;
    @XmlElement(required = true)
    protected SmLineUserCustomer lineUserCustomer;
    @XmlElement(required = true)
    protected String transfererMsisdn;
    @XmlElement(required = true)
    protected SmSubmitGiftCustomer giftReceiverCustomer;
    @XmlElement(required = true)
    protected List<SmSubmitOrderLineItem> orderLineItem;

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductId(BigInteger value) {
        this.productId = value;
    }

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerId(BigInteger value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the contractId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContractId() {
        return contractId;
    }

    /**
     * Sets the value of the contractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContractId(BigInteger value) {
        this.contractId = value;
    }

    /**
     * Gets the value of the crmProductId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrmProductId() {
        return crmProductId;
    }

    /**
     * Sets the value of the crmProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrmProductId(BigInteger value) {
        this.crmProductId = value;
    }

    /**
     * Gets the value of the lineOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineOfferId() {
        return lineOfferId;
    }

    /**
     * Sets the value of the lineOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineOfferId(BigInteger value) {
        this.lineOfferId = value;
    }

    /**
     * Gets the value of the crmProductType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrmProductType() {
        return crmProductType;
    }

    /**
     * Sets the value of the crmProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrmProductType(BigInteger value) {
        this.crmProductType = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductType(BigInteger value) {
        this.productType = value;
    }

    /**
     * Gets the value of the generationReason property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGenerationReason() {
        return generationReason;
    }

    /**
     * Sets the value of the generationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGenerationReason(BigInteger value) {
        this.generationReason = value;
    }

    /**
     * Gets the value of the lifecycleExtended property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLifecycleExtended() {
        return lifecycleExtended;
    }

    /**
     * Sets the value of the lifecycleExtended property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLifecycleExtended(BigInteger value) {
        this.lifecycleExtended = value;
    }

    /**
     * Gets the value of the flowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlowStatus() {
        return flowStatus;
    }

    /**
     * Sets the value of the flowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlowStatus(BigInteger value) {
        this.flowStatus = value;
    }

    /**
     * Gets the value of the flowCurrentProcess property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlowCurrentProcess() {
        return flowCurrentProcess;
    }

    /**
     * Sets the value of the flowCurrentProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlowCurrentProcess(BigInteger value) {
        this.flowCurrentProcess = value;
    }

    /**
     * Gets the value of the codeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodeId() {
        return codeId;
    }

    /**
     * Sets the value of the codeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodeId(BigInteger value) {
        this.codeId = value;
    }

    /**
     * Gets the value of the confirmationType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConfirmationType() {
        return confirmationType;
    }

    /**
     * Sets the value of the confirmationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConfirmationType(BigInteger value) {
        this.confirmationType = value;
    }

    /**
     * Gets the value of the confirmationState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConfirmationState() {
        return confirmationState;
    }

    /**
     * Sets the value of the confirmationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConfirmationState(BigInteger value) {
        this.confirmationState = value;
    }

    /**
     * Gets the value of the confirmationExpireDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConfirmationExpireDate() {
        return confirmationExpireDate;
    }

    /**
     * Sets the value of the confirmationExpireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConfirmationExpireDate(XMLGregorianCalendar value) {
        this.confirmationExpireDate = value;
    }

    /**
     * Gets the value of the distinctConfirmationType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distinctConfirmationType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistinctConfirmationType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitOrderLineDistinctConfirmationType }
     * 
     * 
     */
    public List<SmSubmitOrderLineDistinctConfirmationType> getDistinctConfirmationType() {
        if (distinctConfirmationType == null) {
            distinctConfirmationType = new ArrayList<SmSubmitOrderLineDistinctConfirmationType>();
        }
        return this.distinctConfirmationType;
    }

    /**
     * Gets the value of the lineNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitNotificationDetail }
     * 
     * 
     */
    public List<SmSubmitNotificationDetail> getLineNotification() {
        if (lineNotification == null) {
            lineNotification = new ArrayList<SmSubmitNotificationDetail>();
        }
        return this.lineNotification;
    }

    /**
     * Gets the value of the approveStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApproveStatus() {
        return approveStatus;
    }

    /**
     * Sets the value of the approveStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApproveStatus(Boolean value) {
        this.approveStatus = value;
    }

    /**
     * Gets the value of the productPaymentType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductPaymentType() {
        return productPaymentType;
    }

    /**
     * Sets the value of the productPaymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductPaymentType(BigInteger value) {
        this.productPaymentType = value;
    }

    /**
     * Gets the value of the oldMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldMsisdn() {
        return oldMsisdn;
    }

    /**
     * Sets the value of the oldMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldMsisdn(String value) {
        this.oldMsisdn = value;
    }

    /**
     * Gets the value of the oldSimNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldSimNo() {
        return oldSimNo;
    }

    /**
     * Sets the value of the oldSimNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldSimNo(String value) {
        this.oldSimNo = value;
    }

    /**
     * Gets the value of the newSimNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewSimNo() {
        return newSimNo;
    }

    /**
     * Sets the value of the newSimNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewSimNo(String value) {
        this.newSimNo = value;
    }

    /**
     * Gets the value of the subActionId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubActionId() {
        return subActionId;
    }

    /**
     * Sets the value of the subActionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubActionId(BigInteger value) {
        this.subActionId = value;
    }

    /**
     * Gets the value of the lineUserCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link SmLineUserCustomer }
     *     
     */
    public SmLineUserCustomer getLineUserCustomer() {
        return lineUserCustomer;
    }

    /**
     * Sets the value of the lineUserCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmLineUserCustomer }
     *     
     */
    public void setLineUserCustomer(SmLineUserCustomer value) {
        this.lineUserCustomer = value;
    }

    /**
     * Gets the value of the transfererMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransfererMsisdn() {
        return transfererMsisdn;
    }

    /**
     * Sets the value of the transfererMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransfererMsisdn(String value) {
        this.transfererMsisdn = value;
    }

    /**
     * Gets the value of the giftReceiverCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitGiftCustomer }
     *     
     */
    public SmSubmitGiftCustomer getGiftReceiverCustomer() {
        return giftReceiverCustomer;
    }

    /**
     * Sets the value of the giftReceiverCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitGiftCustomer }
     *     
     */
    public void setGiftReceiverCustomer(SmSubmitGiftCustomer value) {
        this.giftReceiverCustomer = value;
    }

    /**
     * Gets the value of the orderLineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitOrderLineItem }
     * 
     * 
     */
    public List<SmSubmitOrderLineItem> getOrderLineItem() {
        if (orderLineItem == null) {
            orderLineItem = new ArrayList<SmSubmitOrderLineItem>();
        }
        return this.orderLineItem;
    }

}
