//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-submit-customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-submit-customer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="payerMsisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="payerCustomerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="payerContractId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="payerCrmProductId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="payerCrmCustomerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="payerCrmProductType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="crmCustomerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="capturedCustomerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="customerType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="individual" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-individual-customer"/&gt;
 *           &lt;element name="corporate" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-corporate-customer"/&gt;
 *           &lt;element name="individualCorporate" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-individual-corporate-customer"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-submit-customer", propOrder = {
    "payerMsisdn",
    "payerCustomerId",
    "payerContractId",
    "payerCrmProductId",
    "payerCrmCustomerId",
    "payerCrmProductType",
    "crmCustomerId",
    "capturedCustomerId",
    "customerType",
    "individual",
    "corporate",
    "individualCorporate"
})
public class SmSubmitCustomer {

    @XmlElement(required = true)
    protected String payerMsisdn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger payerCustomerId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger payerContractId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger payerCrmProductId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger payerCrmCustomerId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger payerCrmProductType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger crmCustomerId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger capturedCustomerId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger customerType;
    protected SmIndividualCustomer individual;
    protected SmCorporateCustomer corporate;
    protected SmIndividualCorporateCustomer individualCorporate;

    /**
     * Gets the value of the payerMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerMsisdn() {
        return payerMsisdn;
    }

    /**
     * Sets the value of the payerMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerMsisdn(String value) {
        this.payerMsisdn = value;
    }

    /**
     * Gets the value of the payerCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPayerCustomerId() {
        return payerCustomerId;
    }

    /**
     * Sets the value of the payerCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPayerCustomerId(BigInteger value) {
        this.payerCustomerId = value;
    }

    /**
     * Gets the value of the payerContractId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPayerContractId() {
        return payerContractId;
    }

    /**
     * Sets the value of the payerContractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPayerContractId(BigInteger value) {
        this.payerContractId = value;
    }

    /**
     * Gets the value of the payerCrmProductId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPayerCrmProductId() {
        return payerCrmProductId;
    }

    /**
     * Sets the value of the payerCrmProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPayerCrmProductId(BigInteger value) {
        this.payerCrmProductId = value;
    }

    /**
     * Gets the value of the payerCrmCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPayerCrmCustomerId() {
        return payerCrmCustomerId;
    }

    /**
     * Sets the value of the payerCrmCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPayerCrmCustomerId(BigInteger value) {
        this.payerCrmCustomerId = value;
    }

    /**
     * Gets the value of the payerCrmProductType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPayerCrmProductType() {
        return payerCrmProductType;
    }

    /**
     * Sets the value of the payerCrmProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPayerCrmProductType(BigInteger value) {
        this.payerCrmProductType = value;
    }

    /**
     * Gets the value of the crmCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrmCustomerId() {
        return crmCustomerId;
    }

    /**
     * Sets the value of the crmCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrmCustomerId(BigInteger value) {
        this.crmCustomerId = value;
    }

    /**
     * Gets the value of the capturedCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCapturedCustomerId() {
        return capturedCustomerId;
    }

    /**
     * Sets the value of the capturedCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCapturedCustomerId(BigInteger value) {
        this.capturedCustomerId = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerType(BigInteger value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the individual property.
     * 
     * @return
     *     possible object is
     *     {@link SmIndividualCustomer }
     *     
     */
    public SmIndividualCustomer getIndividual() {
        return individual;
    }

    /**
     * Sets the value of the individual property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmIndividualCustomer }
     *     
     */
    public void setIndividual(SmIndividualCustomer value) {
        this.individual = value;
    }

    /**
     * Gets the value of the corporate property.
     * 
     * @return
     *     possible object is
     *     {@link SmCorporateCustomer }
     *     
     */
    public SmCorporateCustomer getCorporate() {
        return corporate;
    }

    /**
     * Sets the value of the corporate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmCorporateCustomer }
     *     
     */
    public void setCorporate(SmCorporateCustomer value) {
        this.corporate = value;
    }

    /**
     * Gets the value of the individualCorporate property.
     * 
     * @return
     *     possible object is
     *     {@link SmIndividualCorporateCustomer }
     *     
     */
    public SmIndividualCorporateCustomer getIndividualCorporate() {
        return individualCorporate;
    }

    /**
     * Sets the value of the individualCorporate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmIndividualCorporateCustomer }
     *     
     */
    public void setIndividualCorporate(SmIndividualCorporateCustomer value) {
        this.individualCorporate = value;
    }

}
