//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-submit-subscriberProv-parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-submit-subscriberProv-parameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="coi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="blocked" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mobileType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uniqueIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="prepaid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="telephoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="givenName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mplusCosId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mplusMoService" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mplusMtService" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-submit-subscriberProv-parameters", propOrder = {
    "coi",
    "blocked",
    "cn",
    "language",
    "mobileType",
    "uid",
    "uniqueIdentifier",
    "sn",
    "prepaid",
    "telephoneNumber",
    "givenName",
    "mplusCosId",
    "mplusMoService",
    "mplusMtService"
})
public class SmSubmitSubscriberProvParameters {

    @XmlElement(required = true)
    protected String coi;
    @XmlElement(required = true)
    protected String blocked;
    @XmlElement(required = true)
    protected String cn;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected String mobileType;
    @XmlElement(required = true)
    protected String uid;
    @XmlElement(required = true)
    protected String uniqueIdentifier;
    @XmlElement(required = true)
    protected String sn;
    @XmlElement(required = true)
    protected String prepaid;
    @XmlElement(required = true)
    protected String telephoneNumber;
    @XmlElement(required = true)
    protected String givenName;
    @XmlElement(required = true)
    protected String mplusCosId;
    @XmlElement(required = true)
    protected String mplusMoService;
    @XmlElement(required = true)
    protected String mplusMtService;

    /**
     * Gets the value of the coi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoi() {
        return coi;
    }

    /**
     * Sets the value of the coi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoi(String value) {
        this.coi = value;
    }

    /**
     * Gets the value of the blocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlocked() {
        return blocked;
    }

    /**
     * Sets the value of the blocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlocked(String value) {
        this.blocked = value;
    }

    /**
     * Gets the value of the cn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCn() {
        return cn;
    }

    /**
     * Sets the value of the cn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCn(String value) {
        this.cn = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the mobileType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileType() {
        return mobileType;
    }

    /**
     * Sets the value of the mobileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileType(String value) {
        this.mobileType = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueIdentifier(String value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the sn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSn() {
        return sn;
    }

    /**
     * Sets the value of the sn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSn(String value) {
        this.sn = value;
    }

    /**
     * Gets the value of the prepaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrepaid() {
        return prepaid;
    }

    /**
     * Sets the value of the prepaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrepaid(String value) {
        this.prepaid = value;
    }

    /**
     * Gets the value of the telephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Sets the value of the telephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumber(String value) {
        this.telephoneNumber = value;
    }

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the mplusCosId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMplusCosId() {
        return mplusCosId;
    }

    /**
     * Sets the value of the mplusCosId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMplusCosId(String value) {
        this.mplusCosId = value;
    }

    /**
     * Gets the value of the mplusMoService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMplusMoService() {
        return mplusMoService;
    }

    /**
     * Sets the value of the mplusMoService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMplusMoService(String value) {
        this.mplusMoService = value;
    }

    /**
     * Gets the value of the mplusMtService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMplusMtService() {
        return mplusMtService;
    }

    /**
     * Sets the value of the mplusMtService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMplusMtService(String value) {
        this.mplusMtService = value;
    }

}
