//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sm-submit-gift-customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sm-submit-gift-customer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="crmCustomerId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="individual" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-gift-individual-customer"/&gt;
 *           &lt;element name="corporate" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-gift-corporate-customer"/&gt;
 *           &lt;element name="individualCorporate" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-gift-individual-corporate-customer"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sm-submit-gift-customer", propOrder = {
    "crmCustomerId",
    "individual",
    "corporate",
    "individualCorporate"
})
public class SmSubmitGiftCustomer {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger crmCustomerId;
    protected SmSubmitGiftIndividualCustomer individual;
    protected SmSubmitGiftCorporateCustomer corporate;
    protected SmSubmitGiftIndividualCorporateCustomer individualCorporate;

    /**
     * Gets the value of the crmCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrmCustomerId() {
        return crmCustomerId;
    }

    /**
     * Sets the value of the crmCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrmCustomerId(BigInteger value) {
        this.crmCustomerId = value;
    }

    /**
     * Gets the value of the individual property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitGiftIndividualCustomer }
     *     
     */
    public SmSubmitGiftIndividualCustomer getIndividual() {
        return individual;
    }

    /**
     * Sets the value of the individual property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitGiftIndividualCustomer }
     *     
     */
    public void setIndividual(SmSubmitGiftIndividualCustomer value) {
        this.individual = value;
    }

    /**
     * Gets the value of the corporate property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitGiftCorporateCustomer }
     *     
     */
    public SmSubmitGiftCorporateCustomer getCorporate() {
        return corporate;
    }

    /**
     * Sets the value of the corporate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitGiftCorporateCustomer }
     *     
     */
    public void setCorporate(SmSubmitGiftCorporateCustomer value) {
        this.corporate = value;
    }

    /**
     * Gets the value of the individualCorporate property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitGiftIndividualCorporateCustomer }
     *     
     */
    public SmSubmitGiftIndividualCorporateCustomer getIndividualCorporate() {
        return individualCorporate;
    }

    /**
     * Sets the value of the individualCorporate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitGiftIndividualCorporateCustomer }
     *     
     */
    public void setIndividualCorporate(SmSubmitGiftIndividualCorporateCustomer value) {
        this.individualCorporate = value;
    }

}
