//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 11:48:52 AM EET 
//


package com.turkcell.playcell.gamingplatform.som.wsdltypes.createorder;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-order-header"/&gt;
 *         &lt;element name="entryUser" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-user"/&gt;
 *         &lt;element name="entryChannelApplication" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-entry-channel-application"/&gt;
 *         &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="synchronous" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="callBackSystemID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="externalDealerCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="documentControlType" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="customer" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-customer"/&gt;
 *         &lt;element name="orderLine" type="{http://extranet.turkcell.com/ordermanagement/processes/serviceordermanagement/ServiceOrderManagementTypes}sm-submit-order-line" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "entryUser",
    "entryChannelApplication",
    "orderId",
    "synchronous",
    "callBackSystemID",
    "externalDealerCode",
    "createDate",
    "dueDate",
    "documentControlType",
    "customer",
    "orderLine"
})
@XmlRootElement(name = "SubmitOrderRequest")
public class SubmitOrderRequest {

    @XmlElement(required = true)
    protected SmSubmitOrderHeader header;
    @XmlElement(required = true)
    protected SmUser entryUser;
    @XmlElement(required = true)
    protected SmEntryChannelApplication entryChannelApplication;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger orderId;
    @XmlElement(defaultValue = "true")
    protected boolean synchronous;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger callBackSystemID;
    @XmlElement(required = true)
    protected String externalDealerCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger documentControlType;
    @XmlElement(required = true)
    protected SmSubmitCustomer customer;
    @XmlElement(required = true)
    protected List<SmSubmitOrderLine> orderLine;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitOrderHeader }
     *     
     */
    public SmSubmitOrderHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitOrderHeader }
     *     
     */
    public void setHeader(SmSubmitOrderHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the entryUser property.
     * 
     * @return
     *     possible object is
     *     {@link SmUser }
     *     
     */
    public SmUser getEntryUser() {
        return entryUser;
    }

    /**
     * Sets the value of the entryUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmUser }
     *     
     */
    public void setEntryUser(SmUser value) {
        this.entryUser = value;
    }

    /**
     * Gets the value of the entryChannelApplication property.
     * 
     * @return
     *     possible object is
     *     {@link SmEntryChannelApplication }
     *     
     */
    public SmEntryChannelApplication getEntryChannelApplication() {
        return entryChannelApplication;
    }

    /**
     * Sets the value of the entryChannelApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmEntryChannelApplication }
     *     
     */
    public void setEntryChannelApplication(SmEntryChannelApplication value) {
        this.entryChannelApplication = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderId(BigInteger value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the synchronous property.
     * 
     */
    public boolean isSynchronous() {
        return synchronous;
    }

    /**
     * Sets the value of the synchronous property.
     * 
     */
    public void setSynchronous(boolean value) {
        this.synchronous = value;
    }

    /**
     * Gets the value of the callBackSystemID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCallBackSystemID() {
        return callBackSystemID;
    }

    /**
     * Sets the value of the callBackSystemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCallBackSystemID(BigInteger value) {
        this.callBackSystemID = value;
    }

    /**
     * Gets the value of the externalDealerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalDealerCode() {
        return externalDealerCode;
    }

    /**
     * Sets the value of the externalDealerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalDealerCode(String value) {
        this.externalDealerCode = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the documentControlType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDocumentControlType() {
        return documentControlType;
    }

    /**
     * Sets the value of the documentControlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDocumentControlType(BigInteger value) {
        this.documentControlType = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link SmSubmitCustomer }
     *     
     */
    public SmSubmitCustomer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmSubmitCustomer }
     *     
     */
    public void setCustomer(SmSubmitCustomer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the orderLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmSubmitOrderLine }
     * 
     * 
     */
    public List<SmSubmitOrderLine> getOrderLine() {
        if (orderLine == null) {
            orderLine = new ArrayList<SmSubmitOrderLine>();
        }
        return this.orderLine;
    }

}
