//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 11:02:22 AM EET 
//


package com.accenture.assets.sdp.commondatamodel.asynch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}TSOheader"/>
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}TSOattributes" minOccurs="0"/>
 *         &lt;element ref="{http://www.accenture.com/assets/sdp/commonDataModel/asynch}TSOresult" minOccurs="0"/>
 *         &lt;element name="DELIVERY_CONTENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tsOheader",
    "tsOattributes",
    "tsOresult",
    "deliverycontent"
})
@XmlRootElement(name = "TSO_DATA")
public class TSODATA {

    @XmlElement(name = "TSOheader", required = true)
    protected TSOheader tsOheader;
    @XmlElement(name = "TSOattributes")
    protected TSOattributes tsOattributes;
    @XmlElement(name = "TSOresult")
    protected TSOresult tsOresult;
    @XmlElement(name = "DELIVERY_CONTENT")
    protected String deliverycontent;

    /**
     * Gets the value of the tsOheader property.
     * 
     * @return
     *     possible object is
     *     {@link TSOheader }
     *     
     */
    public TSOheader getTSOheader() {
        return tsOheader;
    }

    /**
     * Sets the value of the tsOheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSOheader }
     *     
     */
    public void setTSOheader(TSOheader value) {
        this.tsOheader = value;
    }

    /**
     * Gets the value of the tsOattributes property.
     * 
     * @return
     *     possible object is
     *     {@link TSOattributes }
     *     
     */
    public TSOattributes getTSOattributes() {
        return tsOattributes;
    }

    /**
     * Sets the value of the tsOattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSOattributes }
     *     
     */
    public void setTSOattributes(TSOattributes value) {
        this.tsOattributes = value;
    }

    /**
     * Gets the value of the tsOresult property.
     * 
     * @return
     *     possible object is
     *     {@link TSOresult }
     *     
     */
    public TSOresult getTSOresult() {
        return tsOresult;
    }

    /**
     * Sets the value of the tsOresult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSOresult }
     *     
     */
    public void setTSOresult(TSOresult value) {
        this.tsOresult = value;
    }

    /**
     * Gets the value of the deliverycontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVERYCONTENT() {
        return deliverycontent;
    }

    /**
     * Sets the value of the deliverycontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVERYCONTENT(String value) {
        this.deliverycontent = value;
    }

}
