//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 11:02:22 AM EET 
//


package com.accenture.assets.sdp.commondatamodel.asynch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TSOID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TSOlabel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="destinationSystemId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="destinationSystemPassword" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inconcertTaskId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="numberOfAttributes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sequenceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="continueOnFail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rollbackOnError" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="actionReason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="submitTSO" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orderId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MSISDN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IMSI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TSOheader")
public class TSOheader {

    @XmlAttribute(name = "TSOID", required = true)
    protected String tsoid;
    @XmlAttribute(name = "TSOlabel", required = true)
    protected String tsOlabel;
    @XmlAttribute(name = "destinationSystemId")
    protected String destinationSystemId;
    @XmlAttribute(name = "destinationSystemPassword")
    protected String destinationSystemPassword;
    @XmlAttribute(name = "inconcertTaskId")
    protected String inconcertTaskId;
    @XmlAttribute(name = "numberOfAttributes")
    protected String numberOfAttributes;
    @XmlAttribute(name = "sequenceId")
    protected String sequenceId;
    @XmlAttribute(name = "continueOnFail")
    protected String continueOnFail;
    @XmlAttribute(name = "rollbackOnError")
    protected String rollbackOnError;
    @XmlAttribute(name = "actionReason")
    protected String actionReason;
    @XmlAttribute(name = "submitTSO")
    protected String submitTSO;
    @XmlAttribute(name = "orderId")
    protected String orderId;
    @XmlAttribute(name = "MSISDN")
    protected String msisdn;
    @XmlAttribute(name = "IMSI")
    protected String imsi;
    @XmlAttribute(name = "priority")
    protected Integer priority;

    /**
     * Gets the value of the tsoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTSOID() {
        return tsoid;
    }

    /**
     * Sets the value of the tsoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTSOID(String value) {
        this.tsoid = value;
    }

    /**
     * Gets the value of the tsOlabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTSOlabel() {
        return tsOlabel;
    }

    /**
     * Sets the value of the tsOlabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTSOlabel(String value) {
        this.tsOlabel = value;
    }

    /**
     * Gets the value of the destinationSystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationSystemId() {
        return destinationSystemId;
    }

    /**
     * Sets the value of the destinationSystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationSystemId(String value) {
        this.destinationSystemId = value;
    }

    /**
     * Gets the value of the destinationSystemPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationSystemPassword() {
        return destinationSystemPassword;
    }

    /**
     * Sets the value of the destinationSystemPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationSystemPassword(String value) {
        this.destinationSystemPassword = value;
    }

    /**
     * Gets the value of the inconcertTaskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInconcertTaskId() {
        return inconcertTaskId;
    }

    /**
     * Sets the value of the inconcertTaskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInconcertTaskId(String value) {
        this.inconcertTaskId = value;
    }

    /**
     * Gets the value of the numberOfAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfAttributes() {
        return numberOfAttributes;
    }

    /**
     * Sets the value of the numberOfAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfAttributes(String value) {
        this.numberOfAttributes = value;
    }

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceId(String value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the continueOnFail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinueOnFail() {
        return continueOnFail;
    }

    /**
     * Sets the value of the continueOnFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinueOnFail(String value) {
        this.continueOnFail = value;
    }

    /**
     * Gets the value of the rollbackOnError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRollbackOnError() {
        return rollbackOnError;
    }

    /**
     * Sets the value of the rollbackOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRollbackOnError(String value) {
        this.rollbackOnError = value;
    }

    /**
     * Gets the value of the actionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionReason() {
        return actionReason;
    }

    /**
     * Sets the value of the actionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionReason(String value) {
        this.actionReason = value;
    }

    /**
     * Gets the value of the submitTSO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmitTSO() {
        return submitTSO;
    }

    /**
     * Sets the value of the submitTSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmitTSO(String value) {
        this.submitTSO = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMSI(String value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

}
